# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7a70255fea31a9f4cc2908c3fc78eaca369f0f8ef3cc17e8d318b45d3322b1d1c5edbebf9c8ee1d8828d0f1a3565ff84708bada4c27c1e06959249c91057d590

test:
  secret_key_base: a9665475e84e183dddfc499fcd06ca29f0e9974d48f1bf7f1b7452d1a4ef23397e3913b459297324e5a13c229d04e8217c15ff825182b544da64d9cf7d5b70b2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
